# `np.ravel_multi_index` and `np.unravel_index`

[Documentation for `numpy.ravel_multi_index`](https://numpy.org/doc/stable/reference/generated/numpy.ravel_multi_index.html)

[Documentation for `numpy.unravel_index`](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html)

In [1]:
import numpy as np

## `ravel_multi_index`

`np.ravel_multi_index` takes the N-dimensional indices, given by `multi_index`, into an arbitrary array of shape `dims` and converts them into flattened indices into the flattend array.

`multi_index` is a tuple of size N, where N is the number of dimensions. Each element of the tuple is an integer array that represents an index into the corresponding dimension of some arbitrary array.

For instance, if `multi_index = (x0, y0)`, where `x0` and `y0` are integers, it simply represents the index `[x0, y0]` into an arbitrary 2-dimensional array.

But we can specify multiple different indices by giving arrays for each of the elements of the `multi_index` tuple. For instance, `multi_index = ([x0, x1, x2], [y0, y1, y3])` represents three different indices, `[x0, y0]`, `[x1, y1]`, and `[x2, y2]` into an arbitrary 2-dimensional array.

The second argument, `dims`, is a tuple of N integers representing the shape of the array being indexed.

For instance, the index `[x0, y0]` into an array of shape `(dim0, dim1)` becomes the index `x0 * dim1 + y0` into the flattened array of shape `(dim0 * dim1,)`.

In [28]:
np.ravel_multi_index(
    multi_index=([0, 1, 2], [2, 1, 3]),
    dims=(4, 6)
)

array([ 2,  7, 15])

Above, `multi_index=([0, 1, 2], [2, 1, 3])` specifies the three indices `[0, 2]`, `[1, 1]`, and `[2, 3]`. Since `dims[1]=6`, the three indices are converted to the flattened indices, `0 * 6 + 2 = 2`, `1 * 6 + 1 = 7`, and `2 * 6 + 3 = 15`, respectively.

The `multi_index` argument also supports broadcasting--the N different arrays are broadcasted together. The output of `ravel_multi_index` has the shape of the broadcasted index array.

In [30]:
np.ravel_multi_index(
    multi_index=([0, 1, 2], [1]),
    dims=(3, 2),
)

array([1, 3, 5])

Above, after `multi_index=([0, 1, 2], [1])` is broadcasted, it turns into three indices, `[0, 1]`, `[1, 1]`, `[2, 1]`. Those are converted to the flattened indices `0 * 2 + 1 = 1`, `1 * 2 + 1 = 3`, and `2 * 1 + 1 = 5`, respectively.

In [34]:
np.ravel_multi_index(
    multi_index=([0, 1, 2], [[3], [0]]),
    dims=(4, 5),
)

array([[ 3,  8, 13],
       [ 0,  5, 10]])

In this one, `multi_index=([0, 1, 2], [[3], [0]])` broadcasts to six indices, `[0, 3]`, `[1, 3]`, `[2, 3]`, `[0, 0]`, `[1, 0]`, and `[2, 0]`. However, the six indices are arranged in a size `(2, 3)` array, since that is the broadcasted size for the sizes of the two index arrays of size `(3,)` and `(2, 1)`. The broadcasted index array is:

```
[
  [
    [0, 3],
    [1, 3],
    [2, 3],
  ],
  [
    [0, 0],
    [1, 0],
    [2, 0],
  ],
]
```

Then the indices are flattened:

```
[
  [
    0 * 5 + 3,
    1 * 5 + 3,
    2 * 5 + 3,
  ],
  [
    0 * 5 + 0,
    1 * 5 + 0,
    2 * 5 + 0,
  ],
]

= [[3, 8, 13], [0, 5, 10]]
```

## `unravel_index`

`np.unravel_index` is essentially the inverse operator of `np.ravel_multi_index`. Given `indices`, the array of indices into the flattened arbitrary array, and `shape`, the shape of the unflattened arbitrary array, it returns the unflattened indices. The `indices` argument is the output of `np.ravel_multi_index`.

In [36]:
np.unravel_index(
    indices=[[3, 8, 13], [0, 5, 10]],
    shape=(4, 5)
)

(array([[0, 1, 2],
        [0, 1, 2]]),
 array([[3, 3, 3],
        [0, 0, 0]]))

In [47]:
np.unravel_index(
    indices=np.array([[3, 8, 13], [0, 5, 10]]).astype(np.int16),
    shape=(4, 5)
)

(array([[0, 1, 2],
        [0, 1, 2]]),
 array([[3, 3, 3],
        [0, 0, 0]]))